version: '3.3'

networks:
  network-marketplace: ~

services:
  backend:
    networks:
      - network-marketplace
    extra_hosts:
      - host.docker.internal:host-gateway
    build:
      context: ./
      dockerfile: ./docker/php/Dockerfile
      args:
        UID: ${UID}
        GID: ${GID}
        UNAME: ${UNAME}
    container_name: backend-marketplace
    working_dir: /var/www/
    volumes:
      - ./docker/php/config/my.ini:/usr/local/etc/php/conf.d/40-custom.ini
      - ./backend/:/var/www/
      - ./docker/php/logs/:/var/log/php/
    depends_on:
      - database
    environment:
      XDEBUG_MODE: develop,debug
      XDEBUG_CONFIG: client_host=host.docker.internal client_port=9000
      PHP_IDE_CONFIG: serverName=marketplace
    env_file:
      - .env

  nginx:
    networks:
      - network-marketplace
    image: nginx:1.22.1
    container_name: nginx-marketplace
    ports:
      - "49999:80"
    volumes:
      - ./docker/nginx/config/nginx.conf:/etc/nginx/nginx.conf
      - ./docker/nginx/config/conf.d/:/etc/nginx/conf.d
      - ./docker/nginx/certs/:/etc/nginx/certs
      - ./docker/nginx/htpasswd/:/etc/nginx/htpasswd
      - ./docker/nginx/templates/:/etc/nginx/templates
      - ./docker/nginx/logs/:/var/log/nginx
      - ./backend/:/var/www
    depends_on:
      - backend
    environment:
      NGINX_BACKEND_UPSTREAM: backend-marketplace:9000

  database:
    networks:
      - network-marketplace
    image: postgres:15
    container_name: postgres-marketplace
    volumes:
      - /var/lib/postgres-marketplace/:/var/lib/postgresql/data:rw
    ports:
      - "49998:5432"
    environment:
      - POSTGRES_DB=${DB}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
